# Generated by Django 3.1.1 on 2021-01-08 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_name', models.CharField(max_length=50, verbose_name='#Bucket Name')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='About bucket')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.CharField(choices=[('No', 'no'), ('Yes', 'yes')], default='No', max_length=20, verbose_name='is Completed?')),
            ],
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='mybucket', to='todoApp.mybucket')),
                ('todos_name', models.CharField(max_length=50, verbose_name='#to-do name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.CharField(choices=[('No', 'no'), ('Yes', 'yes')], default='No', max_length=20, verbose_name='is Completed?')),
            ],
        ),
    ]
